language: php
php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - CORE_BRANCH=master
  matrix:
  - DB=sqlite

branches:
  only:
    - master

install:
  - mv ../owncloud-owner_fixer ../../owner_fixer
  - wget https://raw.githubusercontent.com/owncloud/administration/master/travis-ci/before_install.sh
  - bash ./before_install.sh owner_fixer $CORE_BRANCH $DB
  - cd ../core
  - php occ app:enable owner_fixer

script:
  # execute unit tests
  - cd apps/owner_fixer/tests;
  - cat Db/*
  - phpunit --configuration phpunit.xml

matrix:
  include:
    - php: 5.6
      env: DB=mysql
    - php: 7.0
      env: DB=mysql
    - php: 7.1
      env: DB=mysql
  fast_finish: true